apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcatuserconf
data:
  tomcat-users.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
      <tomcat-users xmlns="http://tomcat.apache.org/xml"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
                     version="1.0">
        <user username="admin" password="password" roles="admin-gui,manager-gui,manager-script"/>
      </tomcat-users>
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapprs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      volumes:
      - name: tomcatconf
        configMap:
          name: tomcatuserconf
          items:
          - key: "tomcat-users.xml"
            path: "tomcat-users.xml"
      containers:
      - name: javawebapp
        image: rehith4u/java-web-app:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - name: tomcatconf
          mountPath: /usr/local/tomcat/conf/tomcat-users.xml
          subPath: "tomcat-users.xml"
        livenessProbe:
          httpGet:
            path: /java-web-app
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /java-web-app
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080